### ISSUE TITLE
bug: kindd dies when I try to run it

### ISSUE THREAD

**Issue by zombiehoffa** [LinArcX/kindd#16]
Kinda dies when I try to run it, possibly because I am in wayland but I don't really know.  Here's the error:
```
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Could not attach Keys property to:  LinArcxDialog_QMLTYPE_107(0x559d7fb142a0)  is not an Item
qrc:/pages/CreateISO.qml:484:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/pages/CreateISO.qml:476:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/qt/qml/QtQuick/Controls.2/Imagine/ProgressBar.qml:85:52: QML AnimatedImage: Error Reading Animated Image File qrc:/qt-project.org/imports/QtQuick/Controls.2/Imagine/images/progressbar-animation.webp
terminate called after throwing an instance of 'std::regex_error'
  what():  Invalid start of '[x-x]' range in regular expression
[1]    306685 IOT instruction (core dumped)  kindd
```

If you could fix the deprecated properties I would really appreciate it.

**Comment by FunMLG** [comment]
Same in X11...

**Comment by LinArcX** [comment]
Hello. Thanks for reporting the bug.

The reason that I'm not working on this project is that I lose interest in maintaining qt projects in general.

It's a bloated and messy GUI framework that imposes lots of dependencies on the user. And also the Cmake build system. Ow, boy! it's another messy system.

Maybe in near future, I'll re-writing this application with these technologies:
1. [ImGui](https://github.com/ocornut/imgui) as gui toolkit.
2. [Nushell](https://github.com/nushell/nushell) scripts as cross-platfrom build system. (Look at [this beautiful and clean build file](https://github.com/LinArcX/e4/blob/master/build/tools/linux/nu/build.nu))
3. and re-writing the `dd` part all by myself to be cross-platform.

Since then i won't promise to fix any bugs of this project. If i had enough time, i'll do it. But my main focous will be on a better alternative.

**Comment by LinArcX** [comment]
Ok, I found the root of the issue. 

As you can see [here](https://github.com/LinArcX/kindd/blob/master/CMakeLists.txt#L10) I'm using C++17 and C11.

So maybe [your compiler is out of date](https://stackoverflow.com/a/53718169) and you should update it.

I've compiled Kindd on my machine and without any problems it runs and works.

**Comment by FunMLG** [comment]
Ah I see. I don't know why my distro (which is a rolling release though...) uses C++11.
Anyway, I just 'bypassed' the problem by using Ventoy because I absolutely needed to reinstall W$.

You can close the issue now, if it's okay with @zombiehoffa 
I just wanted you to know my situation
